# https://catboost.ai/en/docs/concepts/python-reference_catboostclassifier

_target_: catboost.CatBoostClassifier
n_estimators: 1000
max_depth: 5
learning_rate: 0.5
verbose: 0
loss_function: Logloss
boosting_type: Plain
early_stopping_rounds: 10
subsample: 1.0
colsample_bylevel: 1.0
random_seed: ${seed}
task_type: GPU
reg_lambda: 1
# auto_class_weights: Balanced