# https://xgboost.readthedocs.io/en/stable/python/python_api.html#module-xgboost.sklearn

_target_: xgboost.XGBClassifier
n_estimators: 1000
max_depth: 5
learning_rate: 0.1
verbosity: 0
objective: binary:logistic
booster: gbtree
tree_method: auto
max_leaves: 0
gamma: 
min_child_weight: 
# early_stopping_rounds: 10 # use callbacks instead for consistency with lightgbm
subsample: 1
colsample_bytree: 1